const jobSectors = [
  "Accounting",
  "Administration",
  "Animation",
  "Apparel",
  "Architecture",
  "Arts",
  "Automotive",
  "Aviation",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Business",
  "Capital Markets",
  "Chemicals",
  "Civic",
  "Civil Engineering",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Cosmetics",
  "Dairy",
  "Defense / Space",
  "Design",
  "E - Learning",
  "Education",
  "Electrical",
  "Entertainment",
  "Environmental Services",
  "Events",
  "Executive",
  "Farming",
  "Financial Services",
  "Fishery",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling",
  "Government",
  "Graphic Design",
  "Health Care",
  "Hospitality",
  "Human Resources",
  "Information Technology",
  "Insurance",
  "International Affairs",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Legal Services",
  "Legislative Office",
  "Logistics",
  "Market Research",
  "Marketing",
  "Mechanical Engineering",
  "Media Production",
  "Medical Equipment",
  "Mental Health Care",
  "Military Industry",
  "Mining",
  "Music",
  "Nanotechnology",
  "Non - Profit",
  "Other Industry",
  "Outsourcing",
  "Packaging",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Political Organization",
  "Printing",
  "Professional Training",
  "Program Development",
  "Public Relations",
  "Public Safety",
  "Publishing Industry",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Religious Institutions",
  "Renewables",
  "Research Industry",
  "Restaurants",
  "Retail Industry",
  "Security",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Software Development",
  "Software Engineering",
  "Staffing",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Tobacco",
  "Translation",
  "Transportation",
  "Utilities",
  "Veterinary",
  "Warehousing",
  "Web Development",
  "Wholesale",
  "Writing",
];

export default jobSectors
